site_name: Guararema - Um guia colaborativo
site_url: https://thethales.github.io/guararema/
repo_url: https://github.com/thethales/guararema
repo_name: thethales/guararema
edit_uri: edit/main/src/
site_description: Um guia colaborativo sobre como fazer e contrar as coisas em Guararema São Paulo
site_author: thethales
theme: 
  language: pt
  name: material
  logo: img/logo_white.png
  favicon: img/favicon.ico
  features:
    - navigation.top
    - navigation.sections
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    
docs_dir: src
site_dir: docs
extra:
  disqus: guararema-um-guia-colaborativo
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/umThalesAqui
    - icon: fontawesome/brands/github
      link: https://github.com/thethales/
    - icon: fontawesome/brands/behance
      link: https://www.behance.net/thalessilva
  consent:
    title: Consentimento de Cookies 🍪
    description: Utilizamos cookies para reconhecer suas repetidas visitas e preferências, bem como para medir a eficácia de nossa documentação e se os usuários encontram o que eles estão procurando. Com seu consentimento, você está nos ajudando a melhorar nossa documentação.
extra_javascript:
  - javascript/extra.js
extra_css:
  - stylesheet/extra.css
copyright: GNU GENERAL PUBLIC LICENSE
markdown_extensions:
  - meta
  - attr_list
  - footnotes
  - toc:
      permalink: ⚓︎
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search:
      lang: pt
      prebuild_index: true
nav:
  - Apresentação: 
    - index.md
    - sobre.md
  - Serviços Públicos: 
    - Prefeitura: servicos_publicos.md
    - Ônibus: onibus.md
    - Detran : detran.md
  - Saúde:
    - saude\vacinacao.md
  - Utilidades:
    - Telefones Públicos: prefeitura\telefones_publicos.md
